In [1]:
import numpy as np
from __future__ import print_function
from scipy.stats import chi2
from scipy.stats import rayleigh
from scipy.stats import expon

# Задача 2

In [98]:
# 1
x = np.random.uniform(-3, 2, 10)
print("Выборка:")
print(x, "\n")


def makeConfidenceInterval(x):    
    # 2
    mean = np.mean(x)
    std = np.std(x)
    print("mean={}, Корень из дисперсии данных std={}".format(mean, std))

    # 3
    sq = len(x) ** 0.5 # Корень из длины выборки
    confidence_interval = [mean - 3 * std / sq, mean + 3 * std / sq]
    print("\nДоверительный интервал для среднего по правилу 3 сигма:")
    print(confidence_interval)

    # 4
    print("Попадает ли теор. среднее в интервал? {}".format(confidence_interval[0] <= -0.5 <= confidence_interval[1]))
    
makeConfidenceInterval(x)

Выборка:
[-1.95497216 -1.71733664  1.7681359  -1.00367474  1.19148313 -2.71476567
 -2.37732621 -2.59054689  0.05285058 -0.67436258] 

mean=-1.00205152743, Корень из дисперсии данных std=1.49911680931

Доверительный интервал для среднего по правилу 3 сигма:
[-2.4242386062461172, 0.42013555139174019]
Попадает ли теор. среднее в интервал? True


Теоретическое среднее для равномерного распределения на отрезке $[-3; 2]$ равно $Ex = \frac{a + b}{2} = -0.5$.

Дисперсия равна $Dx = \frac{(b-a)^2}{12} = \frac{25}{12}$ 

$\sqrt{Dx} = 1.4433$

Теоретическое среднее попало в построенный интервал.


In [14]:
def generate(eps, size=10):
    # Строим загрязненную выборку
    x1 = np.random.uniform(-3, 2, size)
    x2 = 5 * np.random.standard_cauchy(size)
    x3 = np.random.binomial(1, eps, size)
    x = x2 * x3 + x1 * (1 - x3)
    return (x, x3)

In [21]:
def dirtyDistribution(eps=0.1, size=10):
    #5
    x, mask = generate(eps, size)

    #6
    print("{}Eps={}{}".format('-' * 20, eps, '-' * 20))
    print(x)
    print("{} - единицы соответсвуют значениям из распределения Коши\n".format(mask))
    makeConfidenceInterval(x)
    print("\n")

In [102]:
#7
for i in range(5):
    dirtyDistribution(0.1, 10)

--------------------Eps=0.1--------------------
[-0.18032977 -9.70748587 -0.70257422  1.08826116 -0.69058521 -1.4228151
 -0.72480342 -2.70714613  1.91064951 -0.61214165]
[0 1 0 0 0 0 0 0 1 0] - единицы соответсвуют значениям из распределения Коши

mean=-1.37489707033, Корень из дисперсии данных std=3.02362190031

Доверительный интервал для среднего по правилу 3 сигма:
[-4.2433566667721134, 1.4935625261160697]
Попадает ли теор. среднее в интервал? True


--------------------Eps=0.1--------------------
[-3.5496746   0.09943215  0.42410004  0.80269291 -2.49511989 -2.11871496
  1.89668315 -0.37465907 -1.39938626 -0.09029439]
[1 0 0 0 0 0 0 0 0 0] - единицы соответсвуют значениям из распределения Коши

mean=-0.680494091569, Корень из дисперсии данных std=1.58815361115

Доверительный интервал для среднего по правилу 3 сигма:
[-2.18714889720912, 0.82616071407160097]
Попадает ли теор. среднее в интервал? True


--------------------Eps=0.1--------------------
[  0.18214444  35.45425495   0.2681

Среднее всегда попадает в интервал, построенный по правилу 3-х сигм. Интервал значительно расширяется, когда в выборке присутствует явный выброс, поэтому в этих случаях, теор. среднее для равномерного распределения все равно попадает в интервал. При небольшом зашумлении эмпирическое среднее не сильно уклоняется от теор. среднего.

In [103]:
# Пункт 8
epsilons = np.linspace(0.1, 0.6, 6)
for eps in epsilons:
    dirtyDistribution(eps)

--------------------Eps=0.1--------------------
[-1.93633196 -1.94667201 -1.14972123 -2.32871629 -0.44189681  0.53030088
  1.14594837 -2.8483293  -0.28728062  1.16057032]
[0 0 0 0 1 0 0 0 0 0] - единицы соответсвуют значениям из распределения Коши

mean=-0.810212865463, Корень из дисперсии данных std=1.38026685435

Доверительный интервал для среднего по правилу 3 сигма:
[-2.1196489770342604, 0.49922324610842761]
Попадает ли теор. среднее в интервал? True


--------------------Eps=0.2--------------------
[ 1.71697081  0.46252778 -3.9933163   0.21748783 -0.15015831  2.69808342
  6.41183453  0.22741643 -0.83873842  0.25805481]
[0 0 1 0 0 1 1 0 0 0] - единицы соответсвуют значениям из распределения Коши

mean=0.701016256665, Корень из дисперсии данных std=2.51946770449

Доверительный интервал для среднего по правилу 3 сигма:
[-1.6891606745610068, 3.0911931878919652]
Попадает ли теор. среднее в интервал? True


--------------------Eps=0.3--------------------
[  1.12707779   0.7637726    5.4

9) Если мы не знаем, что выборка испорчена, то мы получаем оценку для матожидания (хотя его и не существует).

10) Мы видим, что теор. среднее все равно попадает в доверительный интервал.

# Задача 3

In [108]:
def getIntervals(dist, n, **args):
    intervals = []
    for i in range(1, n):
        intervals.append(dist.ppf(float(i) / n, **args))
    return intervals


def getChiStatValue(X, intervals):
    n = len(intervals) + 1
    freq = [0 for i in range(n)]
    for x in X:
        if (x < intervals[0]):
            freq[0] += 1
        else:
            if (x >= intervals[-1]):
                freq[-1] += 1
            else:
                for i in range(1, n - 1):
                    if (intervals[i - 1] <= x < intervals[i]):
                        freq[i] += 1
    
#     print(freq)
    p = 1.0 / n
    total = len(X)
    
    chival = 0.0
    for i in range(n):
        chival += (freq[i] - total * p) ** 2 / (total * p)
    return chival

def chiSquareCrit(x, intervals, statSign):
    chival = getChiStatValue(x, intervals)
    pval = chi2.cdf(chival, len(intervals))
    print(pval)
    return pval <= statSign

Гипотеза $H_0$: наблюдения имеют хи-квадрат распределение с $4$ степенями свободы

In [122]:
#1
x = np.random.chisquare(4, 12)
chiints = getIntervals(chi2, 4, df=4)
#2 
if chiSquareCrit(x, chiints, 0.95):
    print("Принимаем гипотезу H0")
else:
    print("Отвергаем гипотезу H0")

0.656969853862
Принимаем гипотезу H0


Гипотеза $H_1$: наблюдения имеют распределение Рэлея с параметром $a = 3$ 

Гипотеза $H_2$: наблюдения имеют показательное распределение с параметром $\lambda = 0.25$

In [124]:
#3
# генерируем равноверояные интервалы для распределения Рэлея и экспоненциального распределения
rayleighInts = getIntervals(rayleigh, 4, scale = 3)
expInts = getIntervals(expon, 4, scale=1.0/0.25)

if chiSquareCrit(x, rayleighInts, 0.9):
    print("Принимаем гипотезу H1")
else:
    print("Отвергаем гипотезу H1")
    
if chiSquareCrit(x, expInts, 0.9):
    print("Принимаем гипотезу H2")
else:
    print("Отвергаем гипотезу H2")

0.656969853862
Принимаем гипотезу H1
0.80210287379
Принимаем гипотезу H2


In [155]:
#4
baseN = 2
i = 0
flag = True

# Последовательно удваивая добива
while (flag):
    size = baseN * 2 ** i
    print("-----------i={}----Кол-во наблюдений={}---------".format(i, size))
    x = np.random.chisquare(4, size)
    print("Принимаем H0? {}".format(chiSquareCrit(x, chiints, 0.95)))
    i += 1
    
    f1 = chiSquareCrit(x, rayleighInts, 0.9)
    print("Принимаем H1? {}".format(f1))
    f2 = chiSquareCrit(x, expInts, 0.9)
    print("Принимаем H2? {}".format(f2))
    #flag = f1 or f2
    flag = i < 12
    
print(i, baseN * 2 ** i)

-----------i=0----Кол-во наблюдений=2---------
0.427593295529
Принимаем H0? True
0.427593295529
Принимаем H1? True
0.427593295529
Принимаем H2? True
-----------i=1----Кол-во наблюдений=4---------
0.427593295529
Принимаем H0? True
0.427593295529
Принимаем H1? True
0.0
Принимаем H2? True
-----------i=2----Кол-во наблюдений=8---------
0.198748043099
Принимаем H0? True
0.198748043099
Принимаем H1? True
0.608374823729
Принимаем H2? True
-----------i=3----Кол-во наблюдений=16---------
0.78770971264
Принимаем H0? True
0.910337496012
Принимаем H1? False
0.78770971264
Принимаем H2? True
-----------i=4----Кол-во наблюдений=32---------
0.374124546539
Принимаем H0? True
0.919692273445
Принимаем H1? False
0.983443678608
Принимаем H2? False
-----------i=5----Кол-во наблюдений=64---------
0.477832810465
Принимаем H0? True
0.288594809831
Принимаем H1? True
0.958882128608
Принимаем H2? False
-----------i=6----Кол-во наблюдений=128---------
0.440463558687
Принимаем H0? True
0.966252360483
Принимаем H1? 

Видим, что критерий хи-квадрат набирает достаточную статистическую силу при размере выборки в 100 элементов (при разбиении на 4 равновероятных интервала тестируемых распределений). Таким образом, для успешного применения данного критерия у нас должно быть много данных, иначе некоторые распределения будут неотличимы друг от друга.